# Generated by Django 5.2.6 on 2025-09-27 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(default='Empty', max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(default='Empty')),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('aksesoris', 'Aksesoris'), ('sepatu', 'Sepatu'), ('topi', 'Topi'), ('badge', 'Badge')], default='jersey', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('brand', models.CharField(default='Unknown', max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
