# Generated by Django 5.2.6 on 2025-09-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_delete_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Product',
        ),
    ]
